name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rails:
          - '6.1'
          - '7.0'
          - '7.1'
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
    env:
      RAILS_VERSION: ${{ matrix.rails }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: |
        bundle exec rake spec
